### ISSUE TITLE
Add support for arrays.

### ISSUE THREAD

**Issue by toumorokoshi** [aep-dev/aepcli#4]
arrays in objects are common - so how should the CLI handle them?

A few options.

1: comma-separated: `aepcli example books create --authors=alice,bob`

2: multiple arguments: `aepcli example books create --authors=alice --authors=bob`

3: literal json-style arrays: `aepcli example books create --authors=["alice","bob"]`

At this point (1) with a csv-style parsing might be best.

**Comment by rofrankel** [comment]
Sometimes the array is not of primitive types like string, but instead of objects.  How well will that work with option 1?

And if the objects use JSON syntax, then maybe option 3 is a more natural/harmonious fit than option 1.  It seems a bit odd/unprincipled if just the top-level array has a special syntax, but within that array every element is still using standard JSON syntax.
